_BASE_: "../base.yml"

model:
  name: comodgan
  combine_ab: True
  G:
    netG: 'comodgan'
  D:
    netD: 'comodgan'
    epilogue_kwargs:
      mbstd_group_size: 16
loaders:
  batch_size: 16
optimizer:
  lr: 0.0025
scheduler:
  ema:
    enabled: True
    ema_kimgs: 10
    ramp: None

name: 'ixi_comodgan_t2'
