_BASE_: "../base.yml"

model:
  name: stylegan3
  combine_ab: True
  G:
    netG: 'stylegan3'
    img_channels_in: 4
    c_dim: 1
  D:
    netD: 'comodgan'
    img_channels: 5
    c_dim: 1
    epilogue_kwargs:
      mbstd_group_size: 16
loaders:
  batch_size: 16
  slice_num: 4
  thickness: [8,]
  raw_internal_path_in: [T2_FLAIR, ]
  raw_internal_path_out: [T1_HR, ]
optimizer:
  lr_G: 0.0025
  lr_D: 0.002
scheduler:
  n_epochs: 50
  n_epochs_decay: 50
  lr_decay_iters: 50
  ema:
    enabled: True
    ema_kimgs: 10
    ramp: None
loss:
  blur_init_sigma: 10
  blur_fade_kimg: 100
name: 'inhouse_stylegan3_ccsr'
